# Generated by Django 3.0.4 on 2020-04-10 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runfit', '0003_auto_20200410_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coach',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='coach_avatars/'),
        ),
    ]
