# Generated by Django 3.0.4 on 2020-04-13 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runfit', '0005_auto_20200413_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='person_avatars/', verbose_name='Аватар'),
        ),
        migrations.AlterField(
            model_name='person',
            name='phone',
            field=models.CharField(max_length=200, verbose_name='Телефон'),
        ),
    ]
