# Generated by Django 3.0.4 on 2020-04-23 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('runfit', '0010_auto_20200423_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='coach',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='runfit.Coach', verbose_name='Тренер'),
        ),
        migrations.AlterField(
            model_name='order',
            name='pick_training',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='runfit.TypeOfTraining', verbose_name='Тип занятия'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total',
            field=models.FloatField(default=1000, verbose_name='Цена'),
        ),
    ]
